development:
  adapter: postgresql
  encoding: unicode
  database: page_api_development
  host: localhost
  pool: 5
  username: eugene
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: page_api_test
  host: localhost
  pool: 5
  username: eugene
  password: password
